// Emits supabase/seed.sql from lib/data/seed.ts so the two never drift.
// Run: npm run gen:seed   (node --experimental-strip-types)

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  seedRestaurants,
  seedMenuItems,
  seedOffers,
  seedPhotos,
  seedEvents,
  seedReviews,
  SEED_OWNER_IDS,
  SEED_STUDENT_IDS,
} from '../lib/data/seed';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (Array.isArray(v)) return `array[${v.map(q).join(', ')}]::text[]`;
  if (typeof v === 'object')
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const insert = (table: string, rows: Record<string, unknown>[]): string => {
  if (rows.length === 0) return '';
  const cols = Object.keys(rows[0]);
  const values = rows
    .map((r) => `  (${cols.map((c) => q(r[c])).join(', ')})`)
    .join(',\n');
  return `insert into ${table} (${cols.join(', ')}) values\n${values};\n`;
};

const authUser = (
  id: string,
  email: string,
  role: 'student' | 'owner',
  name: string,
) => ({
  id,
  instance_id: '00000000-0000-0000-0000-000000000000',
  aud: 'authenticated',
  role: 'authenticated',
  email,
  encrypted_password: '',
  email_confirmed_at: new Date().toISOString(),
  raw_app_meta_data: { provider: 'email', providers: ['email'] },
  raw_user_meta_data: { full_name: name, role },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});

const owners = SEED_OWNER_IDS.map((id, i) =>
  authUser(
    id,
    `owner${i + 1}@example.com`,
    'owner',
    seedRestaurants[i].name + ' Owner',
  ),
);
const studentNames = ['Ananya', 'Ravi', 'Meghna'];
const students = SEED_STUDENT_IDS.map((id, i) =>
  authUser(
    id,
    `student${i + 1}@student.nitw.ac.in`,
    'student',
    studentNames[i],
  ),
);

// Completed, confirmed bookings backing the seed reviews (review RLS requires them).
const bookings = seedReviews.map((r, i) => ({
  id: r.booking_id,
  student_id: r.student_id,
  restaurant_id: r.restaurant_id,
  headcount: 2 + (i % 3),
  special_request: null,
  booking_time: r.created_at,
  status: 'completed',
  reminder_sent_at: r.created_at,
  confirmed_at: r.created_at,
  owner_note: null,
  owner_note_at: null,
  created_at: r.created_at,
}));

const sql = `-- GENERATED by scripts/generate-seed-sql.ts — edit lib/data/seed.ts and rerun \`npm run gen:seed\`.
-- Dev/local only. Never run against prod (P10-3 removes seed data before launch).

${insert('auth.users', [...owners, ...students])}
-- public.users rows are created by the on_auth_user_created trigger; make sure
-- nitw_verified is set for the seed students.
update users set nitw_verified = true where id in (${SEED_STUDENT_IDS.map(q).join(', ')});

${insert('restaurants', seedRestaurants as unknown as Record<string, unknown>[])}
${insert('menu_items', seedMenuItems as unknown as Record<string, unknown>[])}
${insert('offers', seedOffers as unknown as Record<string, unknown>[])}
${insert('restaurant_photos', seedPhotos as unknown as Record<string, unknown>[])}
${insert('events', seedEvents as unknown as Record<string, unknown>[])}
${insert('bookings', bookings)}
${insert('reviews', seedReviews as unknown as Record<string, unknown>[])}
-- A little view history so trending and analytics have something to chew on.
insert into profile_views (restaurant_id, viewer_id, source_filter, created_at)
select r.id, null, s.source, now() - (random() * interval '48 hours')
from restaurants r
cross join (values ('homepage_feed'), ('search'), ('craving:biryani'), ('events'), ('quiz')) as s(source)
cross join generate_series(1, 4);
`;

const out = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'supabase',
  'seed.sql',
);
writeFileSync(out, sql);
console.log(`wrote ${out}`);
